# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25c672ef4659f41bdbb3e435c5e76aafb25e28fce1a7d1e0e7dec8382c2eb37d7632200d8789055481268e8004868587d81189167acd8c5b28a89920f37d2ac3

test:
  secret_key_base: 30adc19ee38721b4c6a06284d8508ae0be9fd45c7b63e612ca35a99a23c8143255aa807aafce8fe4896692ee4953d966a76a8e2bf9ddd97bbd704c4f834d8379

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
